"""
Precision Oncology Data Architect Assistant — Data Models.

Pydantic models used throughout the pipeline: documents, chunks,
queries, answers, and evaluation results.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Oncology Document
# ---------------------------------------------------------------------------

class OncologyDocument(BaseModel):
    """A document sourced from an oncology data store (e.g. FHIR bundles)."""

    source: str = Field(..., description="File path, URL, or identifier of the source.")
    content: str = Field(..., description="The full text content of the document.")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary metadata (e.g. patient_id, document_type, tumor_type).",
    )

    @field_validator("content")
    @classmethod
    def _content_not_empty(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("Document content must not be empty")
        return stripped

    @field_validator("source")
    @classmethod
    def _source_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Document source must not be empty")
        return v.strip()


# ---------------------------------------------------------------------------
# Chunk
# ---------------------------------------------------------------------------

class Chunk(BaseModel):
    """A single chunk of text (sub‑document) produced by the chunker."""

    text: str = Field(..., description="The chunk text.")
    embedding_id: str = Field(
        ...,
        description="Unique identifier used to store/retrieve the embedding vector.",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata inherited from the parent document plus chunk‑level info.",
    )

    @field_validator("text")
    @classmethod
    def _text_not_empty(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("Chunk text must not be empty")
        return stripped

    @field_validator("embedding_id")
    @classmethod
    def _id_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("embedding_id must not be empty")
        return v.strip()


# ---------------------------------------------------------------------------
# Retrieved Chunk
# ---------------------------------------------------------------------------

class RetrievedChunk(BaseModel):
    """A chunk returned from a similarity search, paired with its score."""

    chunk: Chunk = Field(..., description="The retrieved chunk.")
    score: float = Field(
        ..., ge=0.0, le=1.0, description="Similarity score (0 = dissimilar, 1 = identical)."
    )


# ---------------------------------------------------------------------------
# Query & Answer
# ---------------------------------------------------------------------------

class Query(BaseModel):
    """A user query submitted to the RAG system."""

    text: str = Field(..., description="The raw query text.")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Optional contextual metadata (e.g. conversation_id, patient_id).",
    )

    @field_validator("text")
    @classmethod
    def _text_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Query text must not be empty")
        return v.strip()


class Answer(BaseModel):
    """A system answer generated by the LLM in response to a Query."""

    query: Query = Field(..., description="The original query.")
    answer_text: str = Field(..., description="The generated answer text.")
    retrieved_chunks: List[RetrievedChunk] = Field(
        default_factory=list,
        description="Chunks that were retrieved to support this answer.",
    )
    confidence: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Optional confidence score from the LLM."
    )
    latency_ms: Optional[float] = Field(
        None, ge=0.0, description="End‑to‑end latency of the RAG pipeline in ms."
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    @field_validator("answer_text")
    @classmethod
    def _answer_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Answer text must not be empty")
        return v.strip()

    @model_validator(mode="after")
    def _validate_confidence(self) -> Answer:
        if self.confidence is not None and not (0.0 <= self.confidence <= 1.0):
            raise ValueError("confidence must be between 0 and 1")
        return self


# ---------------------------------------------------------------------------
# Evaluation Result
# ---------------------------------------------------------------------------

class EvaluationResult(BaseModel):
    """Result of evaluating a single query‑answer pair."""

    query: Query = Field(..., description="The query that was evaluated.")
    answer: Answer = Field(..., description="The answer that was evaluated.")
    faithfulness: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Faithfulness / factuality score."
    )
    relevancy: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Answer relevancy score."
    )
    precision: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Context precision score."
    )
    recall: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Context recall score."
    )
    hallucination: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Hallucination rate (lower is better)."
    )
    overall_score: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Aggregate quality score."
    )
    notes: str = Field(
        default="", description="Free‑text notes about this evaluation."
    )

    @model_validator(mode="after")
    def _compute_overall(self) -> EvaluationResult:
        """Auto‑compute overall_score as the average of present metrics."""
        scores = [
            s for s in (self.faithfulness, self.relevancy, self.precision,
                        self.recall, self.hallucination)
            if s is not None
        ]
        if scores and self.overall_score is None:
            self.overall_score = sum(scores) / len(scores)
        return self